name: Build

'on':
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Set up environment variable for Stage Secret
        run: |
          echo "ENV_URL=${{ secrets.DEVURL }}" >> $GITHUB_ENV
      - name: Update fstab.xml with ENV_URL
        run: |
          sed -i "s|\${ENV_URL}|${{ secrets.DEVURL }}|g" fstab.xml
          cat fstab.xml  # To ensure the change was made
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Build application
        run: npm run build  # Make sure you have a build script in package.json
